<a href="https://colab.research.google.com/github/apeetdkl/Python-DS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print(np.__version__)


1.26.4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print (arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
zero_d_array = np.array(194)
print("0D Array (Scalar):")
print(zero_d_array)


one_d_array = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(one_d_array)


two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(two_d_array)

three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(three_d_array)

n = 4
shape = (2,) * n
n_d_array = np.zeros(shape)

print(f"\n{n}D Array (filled with zeros):")
print(n_d_array)

0D Array (Scalar):
194

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4D Array (filled with zeros):
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [ ]:
import numpy as np
array = np.arange(30,)
print (array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [ ]:
import numpy as np

# Create a 0D array (scalar)
zero_d_array = np.array(42)
print("0D Array (Scalar):")
print(zero_d_array)
print("Number of dimensions:", zero_d_array.ndim)  # Check dimensions

# Create a 1D array
one_d_array = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(one_d_array)
print("Number of dimensions:", one_d_array.ndim)  # Check dimensions

# Create a 2D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(two_d_array)
print("Number of dimensions:", two_d_array.ndim)  # Check dimensions

# Create a 3D array (example of an n-D array)
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(three_d_array)
print("Number of dimensions:", three_d_array.ndim)  # Check dimensions

# General approach for creating an n-D array
n = 4  # Desired number of dimensions
shape = (2,) * n  # Create a tuple representing the shape of the array
n_d_array = np.zeros(shape)  # Create an n-D array filled with zeros

print(f"\n{n}D Array (filled with zeros):")
print(n_d_array)
print("Number of dimensions:", n_d_array.ndim)  # Check dimensions

0D Array (Scalar):
42
Number of dimensions: 0

1D Array:
[1 2 3 4 5]
Number of dimensions: 1

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions: 2

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of dimensions: 3

4D Array (filled with zeros):
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
Number of dimensions: 4


Create the array numbers from 0 to 19 and the matrix consist of 4 rows and 5 columns

In [ ]:
import numpy as np
array = np.arange(20)
matrix = array.reshape(4, 5)
print(matrix)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
import numpy as np
array = np.zeros([2,4])
print (array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
array = np.eye(4)
print (array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
array = np.ones([3,6])
print(array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
array = np.full((3),2)
print (array)

[2 2 2]


In [ ]:
import numpy as np
array = np.full([2,2],3)
print(array)

[[3 3]
 [3 3]]


In [ ]:
import numpy as np
array=np.random.rand(2,2,2)
print (array)

[[[0.47281264 0.19607645]
  [0.6113752  0.95075889]]

 [[0.2053919  0.45353531]
  [0.51857269 0.31054977]]]


Create a array with a number of 1,2,3,4,5,6,7 and print the third position element

In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7])
print(array[2])

3


In [ ]:
import numpy as np
array = ([1,2,8,6,5,6,7])
print(array[2:5])

[8, 6, 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,4,5,5])
x = np.where(arr==5)
print(x)

(array([4, 6, 7]),)


Join the array , sort the array, reverse an array

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([3,7,1,0,6])
joined_arr= np.concatenate((arr1, arr2))
sorted_arr = np.sort(arr3)
reverse_arr = joined_arr[::-1]
print(joined_arr)
print(sorted_arr)
print(reverse_arr)

[1 2 3 4 5 6]
[0 1 3 6 7]
[6 5 4 3 2 1]
